name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH로 EC2에 원격 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ screts.EC2_HOST }}
          username: ${{ screts.EC2_USERNAME }}
          key: ${{ screts.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /hme/ubuntu/fitness_booking
            git pull origin main
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &