name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
    steps:
      - name: SSH로 EC2에 원격 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_YML
          script_stop: true
          script: |
            cd /home/ubuntu/fitness_booking
            git pull origin main
            rm -rf src/main/resources/application.yml
            echo "$APPLICATION_YML" > src/main/resources/application.yml
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &