name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
  steps:
    - name: SSH로 Github Actions에서 EC2에 원격 접속하기
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script_stop: true
        scripts: |
          cd /home/ubuntu/fitness_booking
          git pull origin main
          sudo fuser -k -n tcp 8080 || true
          ./gradlew clean build -x test
          nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log >&1  &
